### ISSUE TITLE
Question: How to make it work with asyncio?

### ISSUE THREAD

**Issue by rgreinho** [rsalmei/alive-progress#11]
I have a CLI tool fetching an unknown number of items over an unknown number of pages from an API. The tools uses asyncio (python 3.7) to fetch the data and process it.

I would like to use this progress bar, but when I do, I am facing 2 issues:
1. I have to use sort of a workaround to count the number of items processed asynchronously (see example below).
2. The bar looks super sluggish which does not provide a great user experience. 

Here is a piece of code to simulate my problem with the same symptoms:
```python
import asyncio
import random

from alive_progress import alive_bar


async def fetch_and_process_page(page_number):
    await asyncio.sleep(random.randrange(3))
    return 1


async def main():
    page = 1
    res = []
    with alive_bar(0, spinner="waves") as bar:
        while True:
            tasks = [
                fetch_and_process_page(page)
                for _ in range(random.randrange(5))
            ]
            res += await asyncio.gather(*tasks)

            # Workaround to get the progress bar working.
            for _ in range(len(tasks)):
                bar()

            if random.randrange(12) > 10:
                break
            page += 1
    print(f"{len(res)} items collected.")


asyncio.run(main())
```

Am I using the progress bar correctly? I could not find information regarding its usage with asyncio.

**Comment by rsalmei** [comment]
Hey @rgreinho, you are using it correctly, in the unknown bar mode, where you do not send an expected total.

But actually you've stumbled upon a feature...
The spinner velocity senses and reflects your processing speed. So as you are really processing "few things" per second, the spinner (and the bar itself in the unknown mode) will also run very slowly.

There's nothing special to use it with asyncio, you just need to tick the bar, send a pulse to push it forward. You could for instance call bar() just one time after the `gather` to represent "pages fetched", or several like you did to represent files. You could also get the size of those files and call `bar` the same number of times. This would make the bar swing much faster!

But I think I can improve both problems for you!
I'm going to change the bar signature to `bar(text=None, incr=1)`, that way you can send directly the increment you need, in only one call.

And I'll create the concept of "calibration" of the animation speed. I was thinking about it and it came to me I have implicitly coded that 1.000.000 iterations per second is FAST, so that would equate to the maximum 60 frames per second. Anything less decays logarithmically to the low boundary of 2 frames per second.
But your use-case asks for a FAST threshold that perhaps could be around 50, your ˜super fast" speed... So if your process gets to 50 files per second the bar speed would be around 60 fps...
I think I can do that, I'll include a new keyword argument in `alive_bar` called `calibration=1e6`, to enable the anyone to change that theoretical maximum.

How do these approaches sound to you?

**Comment by rgreinho** [comment]
Thank you very much for the detailed explanations! 

I love the idea of the new signature with `incr` and the calibration concept seems very interesting!

I'm looking forward to implement the future version 👍

**Comment by rsalmei** [comment]
No problem! 😄 

Just to let you know I'm still working on this.
The calibration system proved a little trickier than I thought, I think the logarithm profile won't cut it. I'm studying to change it to a second degree polynomial, a parabola.

I've designed three profiles: log, parabola and linear, all going from (0, 2) to (c, 60), being `c` the user supplied calibration. Here it is:
![image](https://user-images.githubusercontent.com/6652853/64660065-17310100-d415-11e9-9a21-395f27752150.png)

Here is an interactive version, where you can change the calibration:
https://www.desmos.com/calculator/gi2squdobt

That's it...

**Comment by rogerio-geru** [comment]
Well, I've came to the conclusion that the logarithmic profile is actually better for the majority of cases, but in manual mode, where the calibration is 1 (100%), it simply doesn't look like a logarithmic curve anymore:
![image](https://user-images.githubusercontent.com/43352968/64834130-11732100-d5b7-11e9-810e-061e7c544fbd.png)
The parabolic one is actually higher!

Well, the solution was to add another factor into the equation: to calibrations smaller than 100, I did multiply it to get to 100. This is a magic number I've found, that already has its curve stabilized, take a look here: https://www.desmos.com/calculator/pqskbw3uzc
![image](https://user-images.githubusercontent.com/43352968/64934845-e3464900-d823-11e9-8fdb-febfeed435da.png)

**Comment by rsalmei** [comment]
It's alive @rgreinho !
Please install the latest version and let me know! 😅

**Comment by rsalmei** [comment]
Ah, also read the new corresponding readme section: https://github.com/rsalmei/alive-progress#calibration--new

**Comment by rgreinho** [comment]
That looks perfect! And the `bar(incr=)` argument works like a charm too!

Thanks a lot for implementing these new features!

**Comment by rsalmei** [comment]
Great! You're welcome 😉

**Comment by pahrohfit** [comment]
For those coming in late to this, like me, there is a better way by using `asyncio.as_completed()` instead of `asyncio.gather()`, provided you are ok with the caveots of `as_completed()` instead of `gather()`, such as possible out of order results:

```python3
import asyncio
import random

from alive_progress import alive_bar


async def fetch_and_process_page(page_number):
    await asyncio.sleep(random.randrange(3))
    return 1


async def main():
    results = []
    with alive_bar(0, spinner="waves") as bar:
        for task in asyncio.as_completed(
           [fetch_and_process_page(page) for page in range(random.randrange(5))]
        ):

            results.append(await task)
            bar()

    print(f"{len(results)} items collected.")

asyncio.run(main())
```
