### ISSUE TITLE
How to change text placement

### ISSUE THREAD

**Issue by GlenNicholls** [rsalmei/alive-progress#117]
Referencing the example in the docs:

```
with alive_bar(total) as bar:  # declare your expected total
    for item in items:         # <<-- your original loop
        print(item)            # process each item
        bar()                  # call `bar()` at the end
```

>the cool bar.text('message'), which sets a situational message right within the bar, where you can display something about the current item, or the phase the processing is in;

Is it possible to change the text placement to be above or below the bar? My use-case I believe is kind of unique, I opened an issue on stack overflow about [exactly what I'm trying to do](https://stackoverflow.com/questions/70028231/how-to-set-up-progress-bar-and-also-print-output-from-subprocess-popen). In essence, I would like to display just a spinner for a bash command I'm running and then display the text output from that command as a single line below the bar. Then once the command is done executing, that single line "terminal view" goes away.

**Comment by rsalmei** [comment]
Yes, `alive-progress` does support placing texts _above_ it, there's not much sense putting them below, since lines on a terminal run from top to bottom, so the bar has to leave behind all lines printed, like a log.
Today I'm releasing the hiding of the final receipt, and together with spinner hiding, which was already supported, you could do it like this:

![Untitled](https://user-images.githubusercontent.com/6652853/151731714-fdf3db4e-1344-41f0-bd89-ad7f744cb2e3.gif)

I think it is very cool to show the elapsed time, but you can also remove it if you'd like, as well as the "Please wait" message, like this:

![Untitled](https://user-images.githubusercontent.com/6652853/151731957-72ed8abc-0f7b-42a0-a7fd-e4c4476d55be.gif)
