### ISSUE TITLE
Text under progress bar

### ISSUE THREAD

**Issue by mmigliari** [rsalmei/alive-progress#135]
Wouldn't it be nice if while the progress bar is running, right under it you had one line of text which gets updated with a custom message after each bar() call.  Lets call this a "progress text bar"

For example:

```
   with alive_bar(total, progressTextBarTitle='Inserted in DB:') as bar:
       for item from data:
           # do some processing
           bar( progressText=item.text() )
```

Then you would get something like this:
|██████████████            | 4130/5532 [67%] in 43.4s (127.43/s)
[ Inserted in DB:  **license plate ZYZ-999** ]

... and it would be continuously updated just like the progress bar... 

|██████████████            | 4131/5532 [68%] in 43.4s (127.43/s)
[ Inserted in DB:  **license plate ABC-123** ]

... and so son.

So you pass the title for the _progress text bar_ when declaring the alive_bar(), and for each bar() call, you pass it the text that will be displayed in the _progress text bar_, which is a continuously updated text bar right under the progress bar.

While the progress bar is running, right under it you get quickly updating texts explaining what it is doing.  In this example, I would be updating a database, inserting items into it, with the _progress text bar_ listing the titles of the elements I'm inserting into the database.

**Comment by TheTechRobo** [comment]
Isn't there `bar.text()`?

**Comment by rsalmei** [comment]
Yeah, the feature for that is `bar.text`...
I'm not sure it would be that nice for that to be _below_ the bar... 🤔 

Look, this is what I'm talking about:
![Untitled](https://user-images.githubusercontent.com/6652853/152902061-89f24c7e-e142-4b07-9c26-77259ae6e4c1.gif)

**Comment by mmigliari** [comment]
I would love the option to have it under the bar...  The way it is now, there is little space for text, as its competing the with width of the screen used by the progress bar.

**Comment by rsalmei** [comment]
I see. I can try some other time to make a PoC of that, just to see what it would look like...

**Comment by mmigliari** [comment]
Hi, is there an ETA on this?  Thanks!

**Comment by rsalmei** [comment]
Hello @mmigliari,

I did the PoC! It seems to work OK, although personally, I do not like it that much...
Here is how it could look:
![Untitled](https://user-images.githubusercontent.com/6652853/155439012-4c236c72-8ec6-4b0f-8a7f-f61665fa6ef3.gif)

It was a bit harder than I thought, and required a few internal changes that broke some tests and the `showtime()` feature. Also there should be some kind of configuration to opt in to this behavior...
So, there is still some work to do, and I do not have an ETA, since I work on this only in my free time.

But hey, what do you think? Is it what you have imagined?

**Comment by rsalmei** [comment]
It's funny I'm trying to understand for about one hour now, why didn't the cool final receipt appear?
There are subtle implications when using more than one line...

Currently, I've made `alive-progress` printing system like this:
- send to the terminal a `'\r'` to ensure we are on the first column;
- send fragments that are printed one by one, until there is available space;
- if I ran out of fragments, I clear to the end of the line.

It's actually a little more convoluted than that, but it is good for this.
To make the PoC, I've inserted a `'\n'` within the fragments, so the bar text got printed below it, and inserted an ANSI Sequence to send the cursor back up. That's it, I'm not really sure in which column the cursor ends up, but since it will always start with a `'\r'`, I thought it would work...
I didn't understand what happened, nor how to fix it yet 😓

**Comment by rsalmei** [comment]
Got it!!
Required some deeper changes, but now it does work everything:
![Untitled](https://user-images.githubusercontent.com/6652853/155854186-b974842d-3b23-4af0-a96a-881f024161ec.gif)

Even `ctrl_c` works flawlessly:
![Untitled](https://user-images.githubusercontent.com/6652853/155854212-e8fbbf52-bba8-47f1-b70f-515e8a0ca84e.gif)

**Comment by rsalmei** [comment]
Wow, I'm still working on this since my last response! More than 4 hours straight 😓 
It wasn't flawless yet......... I've found several small bugs, like when the current terminal columns cannot fit the whole line, it of course skipped everything from there, which made the second line not print at all.
Then I've noticed that, when `receipt_text=True`, it was duplicating the first line...
It is more complex than I've expected.

**Comment by mmigliari** [comment]
I think its looking really good and will really work for my use case!  Thank you so much for your effort in implementing this!

**Comment by rsalmei** [comment]
I'm glad you liked it.
I'll try to get back to it this weekend and release it.

You're welcome!

**Comment by rsalmei** [comment]
Hey @mmigliari, it's published!! 2.4.0 brings this feature, I called it *Dual Line Text Mode*!

**Comment by mmigliari** [comment]
Amazing.  Thank you so much for your effort and dedication.  Already using it and loving it!

**Comment by rsalmei** [comment]
Thanks, I'm glad you liked it 😛
