### ISSUE TITLE
Some error arise in Jupyter

### ISSUE THREAD

**Issue by hsgyc** [rsalmei/alive-progress#170]
This is an excellent library. When I use this in Jupyter notebook, I meet some problems. First, if I set `dual_line=True`, and set  some strings into `bar.text()`, multi progress bars appear. In fact, each time the text refreshes, it add a new progress bar. Then I use `bar.title()` instead of `bar.text()`. This time, some extra time feadback appear like that.
```
27 |▊    | ▄▆█ 1547/10000 [15%] in 21:02 (1.2/s, eta: 41:51)                                                                98/10000 [1%] in 4s (26.4/s, eta: 1:45) 98/10000 [1%] in 4s (24.7/s, eta: 1:45) 98/10000 [1%] in 4s (21.8/s, eta: 1:45)                                                     (26.9/s, eta: 6:30)    
```
These additional messages are useless and trouble me a lot. It seems like after some times, Jutypter notebook refreshes automatically. How can I solve these problems?

**Comment by rsalmei** [comment]
Hello @hsgyc.

This is not a bug at all. Perhaps I should make it clearer in the readme...
Well, the Jupyter notebook **does not support** control characters in general, only a few.
Mainly, it does not work to move the cursor up (needed for dual-line), and even clear the row (needed ALWAYS).
I could only make `alive-progress` work, by printing a lot of spaces after the bar! A fixed number of spaces, since I also cannot know how long is the row...

You see, there're a lot of compromises in Jupyter.
So, when running in it, you should use the cleanest possible configuration, unfortunately.
