### ISSUE TITLE
Long running threaded jenkins process  with alive-progress leads to timeouts, possibly due to unflushed output.

### ISSUE THREAD

**Issue by IanFoertsch-clumio** [rsalmei/alive-progress#238]
Thanks for making alive-progress available! We love it!

We’re looking at using alive-progress to provide informative progress output in our jenkins pipelines, which execute a series of steps using multiple threads in pipelines that usually last about 45 minutes. We’ve stripped down the config to just output a “heartbeat” progress indicator every 5 seconds, using the following configuration:

```
args = { 'bar' :  None ,  'spinner' :  None ,  'stats' :  False ,  'refresh_secs' :  5}
alive_bar(len(steps), **args)
```

This seems to work for shorter pipelines and tasks, but causes our longer pipelines to become unresponsive and eventually time out. There seems to be something preventing the progress heartbeat from printing to the jenkins console.

Here is an example from the end of a recent pipeline:
```
21:45:20  
Processing 876/904 [97%] in 45:31 
2023-05-02 02:45:20 INFO: <process output>
21:45:20  
2023-05-02 02:45:20 INFO: <process output>
21:45:20  
Processing 876/904 [97%] in 45:31 
2023-05-02 02:45:20 INFO: <process output>
21:45:20  
Processing 876/904 [97%] in 45:31 
2023-05-02 02:45:20 INFO: <process output>
21:45:20  
Processing 876/904 [97%] in 45:31 
2023-05-02 02:45:20 INFO: <process output>
23:57:55  Cancelling nested steps due to timeout
23:57:55  
Processing 877/904 [97%] in 45:32 
Processing 877/904 [97%] in 45:37 
Processing 877/904 [97%] in 45:42 
Processing 877/904 [97%] in 45:47

... 2 hours later ...

Processing 877/904 [97%] in 2:57:42 
Processing 877/904 [97%] in 2:57:47 
Processing 877/904 [97%] in 2:57:52 
Processing 877/904 [97%] in 2:57:57 
Processing 877/904 [97%] in 2:58:02 Sending interrupt signal to process
23:57:55  Killing processes
23:57:55  kill finished with exit code 0
```

As long as our underlying logging system is printing output via python logging:  `2023-05-02 02:45:20 INFO: <process output>`, the alive_progress output is also printed: `Processing 876/904 [97%] in 45:31` , however at the end of the pipeline, no more output is logged, and the alive_progress heartbeat just accumulates, but is not printed until the pipeline terminates due to a configured 3-hour timeout. We’re not exactly sure why the alive_progress output bar causes the pipeline processes to hang, but we believe it may be due to unflushed output. 

Is there any configuration available to force-flush the output?

**Comment by rsalmei** [comment]
Hi @IanFoertsch-clumio, thanks, man!

That's very weird indeed.
Actually, it is not possible for unflushed data to queue up indefinitely because I always flush them, here is the main refresh handler, look how every write is always followed by a flush:
https://github.com/rsalmei/alive-progress/blob/main/alive_progress/core/progress.py#L166-L167

This happens regardless of the kind of terminal that is identified, but I do have four kinds of terminals. In a background Jenkins job I _thought_ it would be getting the `non_tty` one which disables any intermediate updates, only printing the final receipt. But if you do get some "heartbeat" refreshes, the internal update thread should be running, i.e. it did identify it as an interactive terminal.
In this case, write and flush are actually the original methods from `sys.stdout` or `sys.stderr`, as perceived by the Python interpreter itself:
https://github.com/rsalmei/alive-progress/blob/main/alive_progress/utils/terminal/tty.py#L6-L7

I'm not sure what might be happening, but I think Jenkins is doing something funny with the redirections... I'd try changing the `file` param to `stderr`, the default is `stdout`:
https://github.com/rsalmei/alive-progress/blob/main/alive_progress/core/configuration.py#L154

Let me know if it changes anything.

**Comment by rsalmei** [comment]
Well, closing this one. Please reply in case there's any news here.
