### ISSUE TITLE
Make alive_progress celery compatible, i.e. remove `fileno` from file_input_factory check

### ISSUE THREAD

**Issue by HappyCthulhu** [rsalmei/alive-progress#262]
Im wondering, can i get some logging, if alive_bar working inside of celery worker?

With this code:
```
import time

from alive_progress import alive_bar

for x in 1000, 1500, 700, 0:
    with alive_bar(x) as bar:
        for i in range(1000):
            time.sleep(0.005)
            bar()
```

Im getting this error:
![image](https://github.com/rsalmei/alive-progress/assets/23531195/df3cb2b1-654d-4505-b6e2-611eecfc3925)

If im trying to disable it in celery with arg `disable=True`, it doesnt work too. Can i do smth with this?

**Comment by rsalmei** [comment]
It should. However, I see in the celery logging code that they, unfortunately, didn't include a `fileno` method [here](https://github.com/celery/celery/blob/8f389997887232500d4aa1a2b0ae0c7320c4c84a/celery/utils/log.py#L217-L260), which has broken my file validation. That's why `alive_progress` is throwing `ValueError: Invalid config value`.
I can't fix it so it won't break, and can include this fix in the next minor version soon 👍.

But, why would you want to put `alive_progress` in a background async task worker anyway? You won't be able to see it running...

**Comment by HappyCthulhu** [comment]
Is it possible to install version, that contains your fix via pip?

**Comment by rsalmei** [comment]
Unfortunately, not yet. I got sidetracked with other projects and couldn't get back to this yet.

**Comment by rsalmei** [comment]
Hi @HappyCthulhu,
I'm finally releasing this, thanks for your patience.

**Comment by ulgens** [comment]
Hey @rsalmei , we are having this issue with version 3.3.0

> But, why would you want to put alive_progress in a background async task worker anyway? You won't be able to see it running...

In our case, we have multiple data sync operations that can be called manually (via CLI) or periodically (via Celery). It was working just fine with tqdm, but started having

> AttributeError: 'LoggingProxy' object has no attribute 'fileno'

error with alive-progress. 

Is there any known workarounds?

**Comment by rsalmei** [comment]
Hi @ulgens.
Wow, really? I wonder how it could still be trying to use `fileno`...

No workarounds that I know of.
Could you share the whole stack trace?

**Comment by ulgens** [comment]
@rsalmei This should be fixed in https://github.com/rsalmei/alive-progress/pull/300#event-20196251458 Would be nice to have a new patch version with the fix.

**Comment by rsalmei** [comment]
Hey, this should finally be released in the next version!
