### ISSUE TITLE
bar, set to 100% finished even if only passes 80%

### ISSUE THREAD

**Issue by maborak** [rsalmei/alive-progress#39]
Hello, first of all. Congrats for an excellent job.

Second:

I am using the package in a scrapping ebook project where the total of items is not accurate, so at the end the progress bar will show only 80%/100% and end the iteration process

And this is ok. But i want to know if there is a way to tell to bar() that the process is completed and mark it as 100%/100%

Is  that possible?

```python
with alive_bar(total_predicted_items) as bar:
    for page in nop:
        lr.process_page(page_number=page, progressbar=lambda: bar("Processing..."))
    bar() #<-- I want to mark it as 100%

```

Thank you

**Comment by rsalmei** [comment]
> Hello, first of all. Congrats for an excellent job.

Hello man, thank you! Appreciated.

In your example code, since you send pages one by one, I think it would cleaner if you'd put the `bar()` call just after the `process_page`.

Anyway, yes, there *is* a way, just use the `manual` mode! With it you can put the bar in whatever position you like.

So before exiting the `alive_bar` context, you send 100% to it! Something like this:

```python
with alive_bar(total_predicted_items, "Processing...", manual=True) as bar:  # yes, there is a default message.
    for page in nop:  # I'm assuming `page` is an int, since you pass it to `page_number` below.
        lr.process_page(page_number=page)
        bar(page / total_predicted_items)
    bar(1) # marks it to 100% before leaving the context.
```

That's it!
You should even continue to send the predicted total to the starting `alive_bar` call, even being seammingly unnecessary, to still get the throughput and ETA widgets.

You're welcome 👍.

**Comment by rsalmei** [comment]
Hey @maborak, have you had the chance to test it? Did it work now for you?

**Comment by rsalmei** [comment]
Closing this, please reopen if needed 👍
