### ISSUE TITLE
bar(int(10)) Got ERR !  bar(incr=10) - work fine!

### ISSUE THREAD

**Issue by Dinamos** [rsalmei/alive-progress#57]
bar(int(10)) Got ERR ! 
bar(incr=10) - work fine!

**Comment by rsalmei** [comment]
Hey, this is also on the README, see here: https://github.com/rsalmei/alive-progress#displaying-messages

What happens is the `bar` handler has a Deprecated `text` parameter, it was the first way to change the situational message. Now there's the new `bar.text()` to set it.
The second does work because both parameters are optional, the first is `text` and the second `incr`.
Please for now use `incr`, this was improved in 2.0, still not released (#51).
