### ISSUE TITLE
bar() printing position for every item

### ISSUE THREAD

**Issue by underdog** [rsalmei/alive-progress#68]
was just starting to look at using this and ran a couple of your samples on 3 different machines and each one produced the same output.  it was printing "on x: x" where x is the current item number, so "on 1: 1", "on 2: 2", etc... until the end of the loop, at which point I see the bar produced.  looking for answers via search engines didn't give me much help

on 1: 1
.
.
.
on 996: 996
on 997: 997
on 998: 998
on 999: 999
on 1000: 1000
|████████████████████████████████████████| 1000/1000 [100%] in 0.4s (2640.89/s)

**Comment by underdog** [comment]
found this in the progress.py
Not sure where I've configured config.enrich though

header_template = 'on {}: ' if config.enrich_print else ''

**Comment by underdog** [comment]
I used the config_handler to set enrich_print to False and True
When set to "False" it simple prints the number of the item in the list, but when set to True, it goes back to printing the "on 1: 1"...output

**Comment by rsalmei** [comment]
Hey man!
Yeah, I imagine you're using vanilla Python, right?
It's because the ordinary Python REPL tries to print the result of EVERY call being made, unfortunately.
In the ipython, which is the only one I use, it only prints when that would be the final output of a statement.

In Python:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/6652853/103705718-4cf2e500-4f8a-11eb-954d-aa9f79109daa.png">


In ipython:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/6652853/103705658-3187da00-4f8a-11eb-9956-accf32eb1fbf.png">

Well, I had made the `bar()` call return the current line, in case a user would like to know it, since version 1.0.
But given this problem, I did fix it in the next major 2.0, but I'll fix it in the current 1.6 too, and I'll let you know. 👍

**Comment by underdog** [comment]
ok, figured it out.  I was running it within the python console and apparently it prints out every line, as you stated.  running it from a dedicated file works as expected.

consider issue closed.  thanks

**Comment by rsalmei** [comment]
You're welcome man!
For the record, I just fixed it anyway in #70, it will work as expected in python console too!

**Comment by TheTechRobo** [comment]
What I used as an alternative was `fgfg = bar()`. Wasn't pretty but was very simple.

**Comment by rsalmei** [comment]
> What I used as an alternative was `fgfg = bar()`. Wasn't pretty but was very simple.

Cool, I wasn't aware of that hack! Thanks @TheTechRobo 
But thankfully we now have 1.6.2 😄
