### ISSUE TITLE
bar first argument is not incr but text

### ISSUE THREAD

**Issue by sebassdc** [rsalmei/alive-progress#73]
I was trying to use `bar` with a custom int increment. The docs says is the first parameter but instead is the second one.

**Comment by rsalmei** [comment]
Yeah, I know. I'm sorry for that, it is because the first arg `text` is deprecated, and I wanted to show people there the new signature, which will soon be released:

https://github.com/rsalmei/alive-progress/pull/51/files?file-filters%5B%5D=.py#diff-8d1b57093e36209d6147d48384a2a4ebe35764e9d55808de8759904574cc0157R127
