### ISSUE TITLE
There's too much in showtime for my screen ! (1.x)

### ISSUE THREAD

**Issue by TheTechRobo** [rsalmei/alive-progress#78]
sorry for the laggy video.

https://user-images.githubusercontent.com/52163910/105426840-e1f80e00-5c19-11eb-95ad-f52618cb77da.mp4

you get the idea? it flashes since there's too much on screen.

**Comment by rsalmei** [comment]
Hey @TheTechRobo ! How are you man?

Yeah, I know. It is fixed in 2.0, I do need to find some time to release it...
2.0 includes a total overhaul of the showtime tool, it automatically truncates both vertically and horizontally!
So it never skips a beat, flashes or makes the screen scroll, it just shows what fits in your space.

So please hold on a little more, it's soon.

**Comment by TheTechRobo** [comment]
I do definitely think this should be fixed in 1.x, since Python 2.x is still unfortunately widely used.

**Comment by rsalmei** [comment]
Yeah, I see your point.
I'm going to try to backport this, once 2.0 is released 👍

**Comment by paperluigis** [comment]
Mine just SCROLLS

**Comment by TheTechRobo** [comment]
yeah, mine is similar. 

mine flashes between the two screens.

hard to see ANYTHING.

**Comment by rsalmei** [comment]
This is the new one, running on a height constrained window:

https://user-images.githubusercontent.com/6652853/107855867-cbea0180-6e03-11eb-9a9c-f7aad58e891e.mov

**Comment by TheTechRobo** [comment]
nice, is it possible to see the rest after its truncated?

**Comment by rsalmei** [comment]
Yes! If you increase the terminal size while it's running, the rest will nicely appear.

**Comment by rsalmei** [comment]
I'm finishing up 2.0, please hold it just a little more!
Closing this one as it is ready in there!!
