### ISSUE TITLE
Flicker when printing with very slow throughput

### ISSUE THREAD

**Issue by wcmiracle** [rsalmei/alive-progress#83]
![image](https://user-images.githubusercontent.com/5827857/115279792-bb466680-a179-11eb-8498-ef883786a8d3.png)
![11111](https://user-images.githubusercontent.com/5827857/115279818-c0a3b100-a179-11eb-924a-066f6cad845e.gif)

but same code in linux is ok

**Comment by TheTechRobo** [comment]
Hm, that's strange. Hopefully the developer will see this soon because I don't know.

**Comment by rsalmei** [comment]
Hello @wcmiracle ,

That's because this windows terminal does not support ANSI Escape Codes, unfortunately...
Those codes are commands to the terminal, for example to clear the line from the cursor position, clear the entire line, or move the cursor one row up... I do use those, and it seems this terminal just ignores them.

Could you please try the first two answers from here?
https://stackoverflow.com/questions/12492810/python-how-can-i-make-the-ansi-escape-codes-to-work-also-in-windows
I'd like to know if that `os.system('color')` and/or `colorama.init()` do work, so just put them in the same file, before anything.

Also, if you can I'd recommend installing WSL (Windows Subsystem for Linux), which is awesome.

**Comment by wcmiracle** [comment]
**when i add os.system('color') or os.system('')
the program became normal.
 But it’s not smooth enough, it’s flickering, is this normal?**

# Code
```
from alive_progress import alive_bar
import time

with alive_bar(30, bar="smooth") as bar:
    for i in range(30):
        time.sleep(.3)

        bar()
        bar.text("Processing Work #%d" % (i+1))

        print("Work #%d finished" % i)
```

# Win10
![windows](https://user-images.githubusercontent.com/5827857/116343173-8a6bce80-a816-11eb-9454-7910057c1cd3.gif)

# Ubuntu
![ubuntu](https://user-images.githubusercontent.com/5827857/116343188-9061af80-a816-11eb-8801-728d6b091e37.gif)

**Comment by rsalmei** [comment]
Hey, how nice! It did work!!
So I can include this `os` call somewhere, and gain compatibility with Windows at last!
Thank you for testing that.

**Comment by rsalmei** [comment]
Regarding the flickering, I think unfortunately it is normal for this **very slow** refresh rate...
That's because of the dynamic nature of the bar, which updates itself in sync with the throughput. So, when your processing runs at 1.0/s, if there's a `print()` after 100ms of the last refresh, the print is written on the current line of the progress bar, but the next refresh is still 900ms from occurring, which has this flicker effect... 😕 

It should be noticeable only when very slow like that, but there should be something I could do to improve on that!!
I have to think... I should re-print the bar immediately on screen!
Maybe skip the `thread.sleep` of the background thread somehow, or re-print the last progress bar rendered on screen, or maybe printing a fresh new rendition and skipping the next refresh...

Thank you for bringing this up, I'll mark as a bug, and try to fix that somehow 👍

**Comment by rsalmei** [comment]
I think I have the answer! One answer at least...

I can change both the print-hook manager and the bar print engine to turn them together into a producer/consumer architecture of refresh events!
So, they could use a shared lock with a [Condition](https://docs.python.org/3/library/threading.html#condition-objects) object, and both the hook manager and the dynamic refresh engine of the bar will produce refresh events! The bar engine thus wouldn't be called directly anymore, just consume events in another thread.
This should work nicely!

Also, I'd like to investigate how it would be to change both threads to an [async](https://docs.python.org/3/library/asyncio.html) engine! I don't have any expertise in this field, but it should also work to turn these engines into async tasks, and orchestrate them with `await`.

**Comment by rsalmei** [comment]
Oh, and I included this in main `__init__`, should work better on windows now!
```python
# improve windows compatibility, this makes ANSI escape codes work.
import sys

if sys.platform == 'win32':
    import os

    os.system('')
```

**Comment by TheTechRobo** [comment]
That makes ANSI escape codes work? Seems awfully easy.

**Comment by rsalmei** [comment]
Yeah, it seems on windows Python does not request to enable VT100 for console output... And a simple system call does it.
Why doesn't Python call it at the startup? Go figure.
But at least it's simple enough here. 👍

**Comment by rsalmei** [comment]
Hey, I fixed it!!
It is absolutely flawless now, thanks for the report!
![asd](https://user-images.githubusercontent.com/6652853/116943286-a245b700-ac49-11eb-9dd7-d8b5264c3096.gif)

**Comment by rsalmei** [comment]
I'm finishing up 2.0, please hold it just a little more!
Closing this one as it is ready in there!!
